{
  message: "Falled to connect database. Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/",
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'cluster-fasion-shard-00-02.4ijhi.mongodb.net:27017' => ServerDescription {
        address: 'cluster-fasion-shard-00-02.4ijhi.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 46943883,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 13.233.15.36:27017
            at connectionFailureError (C:\Next-level-journey-2023\Mission3 Be a NoSQL Backend Braniac\university-management-auth-server-originalSide\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (C:\Next-level-journey-2023\Mission3 Be a NoSQL Backend Braniac\university-management-auth-server-originalSide\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:510:26)
            at TLSSocket.emit (node:events:390:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21) {
          cause: Error: connect ETIMEDOUT 13.233.15.36:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '13.233.15.36',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'cluster-fasion-shard-00-00.4ijhi.mongodb.net:27017' => ServerDescription {
        address: 'cluster-fasion-shard-00-00.4ijhi.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 46943885,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 13.126.155.22:27017
            at connectionFailureError (C:\Next-level-journey-2023\Mission3 Be a NoSQL Backend Braniac\university-management-auth-server-originalSide\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (C:\Next-level-journey-2023\Mission3 Be a NoSQL Backend Braniac\university-management-auth-server-originalSide\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:510:26)
            at TLSSocket.emit (node:events:390:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21) {
          cause: Error: connect ETIMEDOUT 13.126.155.22:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '13.126.155.22',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'cluster-fasion-shard-00-01.4ijhi.mongodb.net:27017' => ServerDescription {
        address: 'cluster-fasion-shard-00-01.4ijhi.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 46943885,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 13.233.180.9:27017
            at connectionFailureError (C:\Next-level-journey-2023\Mission3 Be a NoSQL Backend Braniac\university-management-auth-server-originalSide\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (C:\Next-level-journey-2023\Mission3 Be a NoSQL Backend Braniac\university-management-auth-server-originalSide\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:510:26)
            at TLSSocket.emit (node:events:390:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21) {
          cause: Error: connect ETIMEDOUT 13.233.180.9:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '13.233.180.9',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-2j927q-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  level: 'error',
  stack: "MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n" +
    '    at _handleConnectionErrors (C:\\Next-level-journey-2023\\Mission3 Be a NoSQL Backend Braniac\\university-management-auth-server-originalSide\\node_modules\\mongoose\\lib\\connection.js:792:11)\n' +
    '    at NativeConnection.openUri (C:\\Next-level-journey-2023\\Mission3 Be a NoSQL Backend Braniac\\university-management-auth-server-originalSide\\node_modules\\mongoose\\lib\\connection.js:767:11)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  label: 'PH',
  timestamp: '2023-06-15T16:32:08.038Z'
}
